### ISSUE TITLE
[Feature] Add parallax affect to the header

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/files-community.github.io#12]
Adding a parallax affect to the header would improve the user experience.

![parallax](https://user-images.githubusercontent.com/39923744/103181177-4cf93380-486c-11eb-9ed6-96b2e0ddf4c6.gif)

**Comment by chingucoding** [comment]
What headers exactly could benefit from a parallax currently? Most pages don't even need scrolling when viewed on 16/9 and the "Edit on github" button would most certainly interfere with the animation if the header is to wide.

**Comment by yaichenbaum** [comment]
@chingucoding This would only be for the home page.

**Comment by chingucoding** [comment]
Got it. Mind if I take a look at this one?

**Comment by yaichenbaum** [comment]
That would be great! Would you like me to assign you the issue?

**Comment by chingucoding** [comment]
Sure, assign this to me.
