### ISSUE TITLE
Alt back and forward shortcuts

### ISSUE THREAD

**Issue by ziyadfarhan296** [files-community/files-community.github.io#58]
# Support to `Alt {back} & {forward}`
I think that it's important to add the Alt back and forward shortcuts to return to the parent folder of a folder if there is. The shortcuts act exactly like the back and forward buttons in the browser. These shortcuts are available in the official explorer and would like to see it here on Files as it's a crucial shortcut for me 😊.

**Comment by yaichenbaum** [comment]
@ziyadfarhan296 This shortcut should be available in the latest version of Files (v1.3).
