### ISSUE TITLE
MS OneDrive not showing up in "Files" application.

### ISSUE THREAD

**Issue by mbuschagen** [files-community/files-community.github.io#65]
I recently discovered the "Files" application and started using it instead of Windows Explorer. However, in Files, I cannot find the setting is to display the MS OneDrive folders. I would like to stop using Windows Explorer, but I need to have access to my OneDrive files.

Please see the screenshots of OneDrive showing up in "Explorer" and not showing OneDrive in "Files."

![Files](https://user-images.githubusercontent.com/80843256/111838119-1acd0000-88b6-11eb-80b3-73715a908fbc.png)
![Explorer](https://user-images.githubusercontent.com/80843256/111838129-1ef91d80-88b6-11eb-9278-d433b8374c0e.png)

Thanks in advance for your help.

**Comment by techtanic** [comment]
This repo is ONLY for website related issues
https://github.com/files-community/Files/issues/3659
