### ISSUE TITLE
Status Column for SharePoint syncs

### ISSUE THREAD

**Issue by HakeemAzma** [files-community/files-community.github.io#69]
Synced folders from SharePoint under Cloud Drives do not have a Status folder at the root directory. However, once in each folder, status column shows up for individual files as usual.

Other OneDrive (both Personal and Work) has it.

**Comment by yaichenbaum** [comment]
@HakeemAzma This is the wrong repo for this kind of issue, can you please open an issue on the main Files repo? https://github.com/files-community/Files
