### ISSUE TITLE
Doesn't Support High Refresh Rate (G-SYNC, etc)

### ISSUE THREAD

**Issue by phendrome** [files-community/files-community.github.io#71]
# <Your issue Title>
When you open Files, the refresh rate drops considerably. 

Tried to tinker with the NVIDIA Control Panel under these settings:

- Manage 3D Settings
- Program Settings
- Selected Files under "Select a program to customize"
- Under "Specify the settings for this program"
- Changed "Preferred refresh rate" to "Highest available" and the other options
- Changed "Vertical sync" to "Off/On/Fast"

Nothing seem to have helped. Still lags and drops down the refresh rate considerably.

**Comment by phendrome** [comment]
Worth noting, using a 144Hz monitor, more specifically "AOC G2460" and I've got a GTX 980.

**Comment by yaichenbaum** [comment]
@phendrome This is the wrong repo for this kind of issue, can you open a new issue [here](https://github.com/files-community/Files)?
