### ISSUE TITLE
Add a sponsor button

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/files-community.github.io#74]
Adding a link to sponsor the project through PayPal will make it easier for users to discover how they can help fund the development of Files.

**Comment by chingucoding** [comment]
Do you want to add the sponsor button on the GitHub repo or the actual website?

**Comment by yaichenbaum** [comment]
We already have one on the Files app repo, this proposal is to add it to the website.

**Comment by chingucoding** [comment]
I think there are three ways we could include this on the mainpage (numbered 1 to 3 in the screenshot below):
![Screenshot showing the three possible solutions for the sponsor button](https://user-images.githubusercontent.com/16122379/115158425-53672180-a08e-11eb-9e91-2e9a5c098d2c.png)

I think 1 is to "in your face", if the first input for files also contains the sponsor link, I don't think that is ideal. Option 3 is probably to hidden as it is in the footer. I would favor option 2 but maybe other folks have other ideas.

**Comment by yaichenbaum** [comment]
I think the third option is the best one as option 1 isn't ideal, and option 2 would look a little crowded.

**Comment by chingucoding** [comment]
Should it be text with icon or just icon? If with text, can you provide the wording for this @yaichenbaum ?

**Comment by yaichenbaum** [comment]
I think an icon would be better so that it would fit in with the other items in the footer.
