### ISSUE TITLE
box cloud-I can't see files or folders

### ISSUE THREAD

**Issue by valdo65** [files-community/files-community.github.io#91]
Hi, first of all I love your file manager, great job. The problem I have is that I use box (box.com) as a cloud service, I can see it in the cloud drive panel, but when I try to reach some file or folder in the box, I can only see the first folder (I have many more in the root directory) but even when I try to access that folder it shows it totally empty. Also try following the path where the files are on the hard drive ex: D: \ Cloud \ Box, but I can't see any files or folders either.
A clarification, which may help you, I use Box Drive (provided by box.com which allows you to access the files without occupying space on disk, similar to the function of onedrive free up space, so the files only download them to your disk when you need it.
I don't have this problem with the windows file exporer

Thank's

**Comment by chingucoding** [comment]
Hi @valdo65 , this repository is only for the Files website, for bug reports and questions, please file an issue over at the Files repository: https://github.com/files-community/files
