### ISSUE TITLE
Closing Tab (CTRL W) closes the app

### ISSUE THREAD

**Issue by MarathonMax** [files-community/files-community.github.io#92]
I have two panes open, left, right. Hitting CTRL W closes the window, not the right tab... or how do I get back to a single pane opened ?

**Comment by pklion** [comment]
This is not the repository for bug reporting, please report it to [here](https://github.com/files-community/Files/issues) .

**Comment by chingucoding** [comment]
As @pklion correctly pointed out, this repository is not for Files itsself. This repository only contains the code of the Files website, for bug reports, please file an issue here: https://github.com/files-community/Files
